### ISSUE TITLE
Supervised loss or Unsupervised loss

### ISSUE THREAD

**Issue by lithostark** [yshenaw/GNN-Resource-Management#1]
Hi, nice work and thank you for sharing the code.

I got confused about the loss you are using. In the paper, it is claimed that an unsupervised loss is used. But the loss function "sr_loss()" requires the label. Could you provide some illustrations? Many thanks~

https://github.com/yshenaw/GNN-Resource-Management/blob/ea5e2355ba5f9aace9aaab7e844537784075a6a1/D2D/Beamforming/main.py#L198-L202

**Comment by yshenaw** [comment]
Hi, y is the data instead of the label. I just name the variable as 'y'.

**Comment by lithostark** [comment]
> Hi, y is the data instead of the label. I just name the variable as 'y'.

Thank you for the quick response! Problem solved~
